apiVersion: v1
kind: Service
metadata:
  name: k8s-backend-user-jdbc-service
spec:
  ports:
    - port: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-backend-user-jdbc-service
subsets:
  - addresses:
      - ip: 192.168.0.112
    ports:
      - port: 13306