apiVersion: v1
kind: Service
metadata:
  name: k8s-external-user-mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 13306
  clusterIP: None
---

apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-external-user-mysql-service
subsets:
  - addresses:
      - ip: 192.168.0.112
    ports:
      - port: 13306